package com.example.androidappdevelopmentusinggenai_namma_shaaleinventory.util

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import com.example.androidappdevelopmentusinggenai_namma_shaaleinventory.data.Asset
import java.io.File
import java.io.FileOutputStream
import java.text.DateFormat
import java.util.Date

object PdfGenerator {
    fun generateInventoryPdf(
        context: Context, 
        assets: List<Asset>, 
        institutionName: String = "All Institutions",
        startDate: Long? = null,
        endDate: Long? = null
    ): File? {
        val filteredAssets = assets.filter {
            val dateMatch = if (startDate != null && endDate != null) {
                it.lastChecked in startDate..endDate
            } else true
            dateMatch
        }

        val pdfDocument = PdfDocument()
        val paint = Paint()
        val titlePaint = Paint()

        // Page info: A4 size is roughly 595 x 842 at 72dpi
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        // Header
        titlePaint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        titlePaint.textSize = 24f
        titlePaint.color = Color.BLACK
        canvas.drawText("AUDIT REPORT: $institutionName", 50f, 50f, titlePaint)

        paint.textSize = 12f
        paint.color = Color.DKGRAY
        canvas.drawText("Generated on: ${DateFormat.getDateTimeInstance().format(Date())}", 50f, 75f, paint)

        if (startDate != null && endDate != null) {
            val df = DateFormat.getDateInstance()
            canvas.drawText("Period: ${df.format(Date(startDate))} - ${df.format(Date(endDate))}", 50f, 95f, paint)
        }

        // Statistics
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        paint.textSize = 14f
        canvas.drawText("Inventory Statistics:", 50f, 130f, paint)
        
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        paint.textSize = 12f
        canvas.drawText("- Total Assets: ${filteredAssets.size}", 60f, 150f, paint)
        canvas.drawText("- Working: ${filteredAssets.count { it.condition == "Working" }}", 60f, 170f, paint)
        canvas.drawText("- Needs Repair: ${filteredAssets.count { it.condition == "Needs Repair" }}", 60f, 190f, paint)
        canvas.drawText("- Broken: ${filteredAssets.count { it.condition == "Broken" }}", 60f, 210f, paint)

        // Table Header
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        canvas.drawText("Asset Details:", 50f, 250f, paint)
        
        var yPos = 280f
        paint.textSize = 10f
        canvas.drawText("ID", 50f, yPos, paint)
        canvas.drawText("Name", 80f, yPos, paint)
        canvas.drawText("Category", 250f, yPos, paint)
        canvas.drawText("Condition", 380f, yPos, paint)
        canvas.drawText("Serial No.", 480f, yPos, paint)
        
        canvas.drawLine(50f, yPos + 5f, 550f, yPos + 5f, paint)
        yPos += 20f

        // Table Rows
        paint.typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
        filteredAssets.forEachIndexed { index, asset ->
            if (yPos > 800) { // Simple pagination check
                // In a real app, we would start a new page here
                return@forEachIndexed 
            }
            canvas.drawText("${index + 1}", 50f, yPos, paint)
            canvas.drawText(asset.name.take(25), 80f, yPos, paint)
            canvas.drawText(asset.category, 250f, yPos, paint)
            canvas.drawText(asset.condition, 380f, yPos, paint)
            canvas.drawText(asset.serialNumber.take(15), 480f, yPos, paint)
            yPos += 20f
        }

        // Footer
        paint.textSize = 8f
        paint.color = Color.GRAY
        canvas.drawText("This is an official digital audit report generated by Namma-Shaale Inventory App.", 50f, 820f, paint)

        pdfDocument.finishPage(page)

        // Save to internal storage
        val directory = File(context.filesDir, "reports")
        if (!directory.exists()) directory.mkdirs()
        
        val file = File(directory, "Inventory_Report_${System.currentTimeMillis()}.pdf")
        return try {
            pdfDocument.writeTo(FileOutputStream(file))
            pdfDocument.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            pdfDocument.close()
            null
        }
    }
}